# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_Details',
        ),
    ]
