# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0002_auto_20180202_1959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Details',
        ),
    ]
