# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useract', '0003_delete_user_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=500)),
                ('user_name', models.CharField(max_length=500)),
                ('pass_word', models.CharField(max_length=500)),
            ],
        ),
    ]
