# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-04 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0007_auto_20180204_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='password',
        ),
    ]
