# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-23 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0009_auto_20180223_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('e_mail', models.EmailField(max_length=254)),
                ('pass_word', models.CharField(max_length=10000)),
                ('nic_no', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Admin',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('e_mail', models.EmailField(max_length=254)),
                ('pass_word', models.CharField(max_length=10000)),
                ('nic_no', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Customer',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useract.Customer'),
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
