# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-24 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0010_auto_20180223_2221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='report_id',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='authority_id',
        ),
        migrations.DeleteModel(
            name='Authority',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
