# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-24 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0015_auto_20180224_2014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='user_id',
            new_name='USERNAME',
        ),
    ]
