# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-11 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0016_auto_20180224_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
