# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-11 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0017_inquiry_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='dateTime',
        ),
    ]
