# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-11 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0020_auto_20180311_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abc',
        ),
    ]
