# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-11 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0022_remove_inquiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='time',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
