# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-11 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0023_inquiry_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='time',
        ),
    ]
