# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-13 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0024_remove_inquiry_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='USERNAME',
            new_name='user_id',
        ),
    ]
