# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-13 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0025_auto_20180313_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='user_id',
            new_name='username',
        ),
    ]
