# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-13 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0027_auto_20180313_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='user',
            new_name='username',
        ),
    ]
