# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-13 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0028_auto_20180313_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='username',
            new_name='USERNAME',
        ),
    ]
