# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0033_table1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table1',
        ),
    ]
