# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-31 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0034_delete_table1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_number', models.CharField(max_length=10)),
                ('bus_name', models.CharField(max_length=1000)),
                ('route', models.CharField(max_length=10)),
            ],
        ),
    ]
