# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-31 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0035_bus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bus',
            new_name='useract_Bus',
        ),
    ]
