# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-31 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0036_auto_20180331_2045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='useract_Bus',
        ),
    ]
