# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-12 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0037_delete_useract_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
