# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-19 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sen_id', models.IntegerField(max_length=50, unique=True)),
                ('sentence', models.CharField(max_length=100000)),
                ('class_id', models.IntegerField()),
                ('layer_id', models.IntegerField()),
            ],
        ),
    ]
