# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-19 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='sen_id',
            field=models.IntegerField(unique=True),
        ),
    ]
