# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-19 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_train_class_bag'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='word_bag',
            field=models.CharField(max_length=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='class_bag',
            field=models.CharField(max_length=100000000, null=True),
        ),
    ]
