# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-23 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useract', '0008_remove_userdetail_password'),
        ('chatbot', '0005_auto_20180219_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('authority_id', models.IntegerField(primary_key=True, serialize=False)),
                ('authority_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10000)),
                ('e_mail', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('inquiry_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('add_state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Layers',
            fields=[
                ('layer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('layer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('authority_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Authority')),
            ],
        ),
        migrations.RemoveField(
            model_name='train',
            name='id',
        ),
        migrations.AlterField(
            model_name='train',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Classes'),
        ),
        migrations.AlterField(
            model_name='train',
            name='layer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Layers'),
        ),
        migrations.AlterField(
            model_name='train',
            name='sen_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Report'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useract.UserDetail'),
        ),
    ]
