# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-23 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_auto_20180223_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synapsys',
            fields=[
                ('syn_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('data_array', models.CharField(max_length=500)),
            ],
        ),
    ]
