# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-23 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_synapsys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='report_id',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='authority_id',
        ),
        migrations.DeleteModel(
            name='Authority',
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
