# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_classes_layer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='layer_id',
        ),
    ]
