# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_remove_classes_layer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='sets',
            fields=[
                ('set_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Classes')),
                ('layer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Layers')),
            ],
        ),
    ]
