# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_sets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sets',
            old_name='class_id',
            new_name='class_id_of',
        ),
        migrations.RenameField(
            model_name='sets',
            old_name='layer_id',
            new_name='layer_id_of',
        ),
        migrations.RemoveField(
            model_name='train',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='train',
            name='layer_id',
        ),
        migrations.AddField(
            model_name='sets',
            name='parent_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='set_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatbot.sets'),
            preserve_default=False,
        ),
    ]
