# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_auto_20180310_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='layers',
            name='layer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sets',
            name='set_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='synapsys',
            name='syn_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='train',
            name='sen_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
