# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_auto_20180310_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='sen_id',
            new_name='sentence_id',
        ),
    ]
